### ISSUE TITLE
Access requests

### ISSUE THREAD

**Issue by AlbinTheander** [echsylon/atlantis#8]
If I use Atlantis for testing, it would be handy to be able to access the requests to validate that they are correct.

For testing purposes, it would be great if they were available after the test, so you could write tests similar to:

```java
public void testRequestAsksForJson() {
  startAtlantis();
  myCoolRequester.getData();

  Request[] requests = atlantis.getRequests();
  assertEquals(requests.length, 1);
  Map<String, String> headers = requests[0].getHeaders();
  assertEquals(headers.get('accept'), 'application/json');
}
````

**Comment by echsylon** [comment]
Good point!

Since it's fair to assume the author of the test has knowledge of the `myCoolRequester.getData()` implementation - especially what requests it's making - would it make sense to perhaps even specify *which* request to get from `Atlantis`, saving the user the hassle of searching a list? Something like:

```java
Request request = atlantis.getRequest("get", "http://localhost/path?query=yes#fragment",
        new Header("k1", "v1"),
        new Header("k2", "v2"));
...
```

**Comment by AlbinTheander** [comment]
It could certainly be convenient to search for requests by different criteria, but I think an array (or list, or iterator, or similar) would be needed. I've used "request capturing" previously to verify:

* That the correct header were sent (e.g. checking that "Accept-encoding: gzip" was added.)
* That the number of requests being made were correct
* That two requests were made in the correct order

Probably more things as well.

So, those are use cases that I, personally, would like to solve. :-)

Another handy thing would be to be able to start and stop request capturing. That way you wouldn't have to restart the server for each test case.

**Comment by laszlourszuly** [comment]
Ah! It turns out I misunderstood your initial intention with this ticket. It all seems much clearer now at least: `atlantis.getRequests()`, as in your example, would return any *served requests*, not the successfully parsed template requests to match against. And in this context a `startCapture()` and a `stopCapture()` would make sense, where the `stopCapture()` also would clear the history stack.

Given this new perspective, it all makes much more sense...

**Comment by echsylon** [comment]
Or even better: `startCapture()` should clear the history stack.
